global:
  # Intervalo de raspagem de métricas. O padrão é a cada 60s
  scrape_interval:  10s
  # Intervalo para avaliação de regras. O padrão é a cada 60s
  evaluation_interval: 10s
  # scrape_timeout é definido como o padrão global (10s).

scrape_configs:
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    #    scheme defaults to 'http'.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.102:8085']