server:
  port: 8085



management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-origins: '*'
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      aplicacao: serviço de testes
      ambiente: desenvolvimento
  endpoint:
    prometheus:
      enabled: true
